### ISSUE TITLE
needs clearer instructions

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/objc-dictionary-ice-cream#2]
Would be helpful to describe what the methods will do upfront, before you break down the step by step process. I had trouble thinking about what to name the arguments that I would give my methods in their definitions because I wasn't 100% on what I wanted my methods to eventually do. 

Second method was tough, could have used some more hand-holding/hints. 

@markedwardmurray

**Comment by markedwardmurray** [comment]
add argument  names to instructions. improved hint to second method challenge.
